(function(globalObject) {
﻿//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

    globalObject.CSReportWebServer.Properties = globalObject.CSReportWebServer.Properties || {};


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    globalObject.CSReportWebServer.Properties.createPartial = function() {

        // @ts-ignore
        let self: CSReportWebServer.Properties.Ipartial = {};

        let Settings: static defaultInstance = ((global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

UNKNOWN >>         public static Settings Default {
UNKNOWN >>             get {
                return defaultInstance;

        };

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gfladhgjbflfogopjcjkmokdddcboika")]
UNKNOWN >>         public string ExtensionId {
UNKNOWN >>             get {
                return ();
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
UNKNOWN >>         [global::System.Configuration.DefaultSettingValueAttribute("MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDcBHwzDvyBQ6bDppkIs9MP4ksKqCMyXQ/A52JivHZKh" +
            "4YO/9vJsT3oaYhSpDCE9RPocOEQvwsHsFReW2nUEc6OLLyoCFFxIb7KkLGsmfakkut/fFdNJYh0xOTbS" +
            "N8YvLWcqph09XAY2Y/f0AL7vfO1cuCqtkMt8hFrBGWxDdf9CQIDAQAB")]
UNKNOWN >>         public string ExtensionKey {
UNKNOWN >>             get {
                return ();
            }
UNKNOWN >>             set {
                this["ExtensionKey"] = value;
            }
        }
        return self;

    }    }
}(globalObject));


namespace CSReportWebServer.Properties {

  export interface Ipartial {

  }
}
