
﻿//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSReportEditor.Properties {


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    export class partial {



        private Settings: static defaultInstance = ((global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

UNKNOWN >>         public static Settings Default {
UNKNOWN >>             get {
                return defaultInstance;
            }
        }


    }    }
}
