(function(globalObject) {
﻿//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

    globalObject.CSAssocFile.Properties = globalObject.CSAssocFile.Properties || {};


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    globalObject.CSAssocFile.Properties.createResources = function() {

        const self = {};

        let global::System.Resources.ResourceManager resourceMan = null;

        let global::System.Globalization.CultureInfo resourceCulture = null;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        const Resources = function() {

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
UNKNOWN >>         internal static global::System.Resources.ResourceManager ResourceManager {
UNKNOWN >>             get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    let temp = new global::System.Resources.ResourceManager("CSAssocFile.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;

                return resourceMan;
            }
        };

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
UNKNOWN >>         internal static global::System.Globalization.CultureInfo Culture {
UNKNOWN >>             get {
                return resourceCulture;
            }
UNKNOWN >>             set {
                resourceCulture = value;
            }
        }

UNKNOWN >>         internal static System.Drawing.Bitmap question2 {
UNKNOWN >>             get {
                let obj = ResourceManager.GetObject("question2", resourceCulture);
                return ();
            }
        }
        return self;

    }
}(globalObject));
