
﻿//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.3603
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CSDataBase
{


    export class cOpenRsCommand {


    {
        private c_module: string = "cDataBase";

//         private delegate DbDataReader delegateAsyncOpenRsEx(string sqlstmt);

        private invoke: delegateAsyncOpenRsEx = null;
        private ors: DbDataReader = null;
        private sqlstmt: string = "";
        private done: boolean = false;

UNKNOWN >>         public bool done
        {
UNKNOWN >>             get { return this.done; }
        }

UNKNOWN >>         public bool success
        {
UNKNOWN >>             get { return this.ors !== null; }
        }

UNKNOWN >>         public DbDataReader ors
        {
UNKNOWN >>             get { return this.ors; }
        }

        public getExecuteCommand(db: cDataBase, sqlstmt: string) {
            this.sqlstmt = sqlstmt;
            this.invoke = new delegateAsyncOpenRsEx(db.asyncOpenRsEx);
        }

        public execute() {
            try {
                this.invoke.BeginInvoke(this.sqlstmt, this.callBack, null);
            }
            catch (ex) {
                cError.mngError(ex, "execute", c_module, "");
            }
        }

        private callBack(ar: IAsyncResult) {
            try {
                this.ors = this.invoke.EndInvoke(ar);
                this.done = true;
            }
            catch (ex) {
                cError.mngError(ex, "callBack", c_module, "");
            }
        }

        public constructor() {
        }


    }    }
}
