
﻿//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.3603
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------



namespace CSKernelClient
{


    export class cRegionalCfg {


    {

        private string: static this.decimalPoint = "";
        private c_error_1: string = "No se pudo determinar cual es el separador decimal. Confirme en el 'panel de control/configuración regional' que los valores de la ficha número coincidan con los valores de la ficha moneda en los campos 'simbolo decimal' y 'simbolo de separación de miles'.";
        private c_error_2: string = "Se debe invocar el metodo init de la clase cReginalCfg de la dll CSKernelClient, antes de utilizar cualquier metodo que invoque a la propiedad decimalPoint.";

        public init() {
            double number; {

            double.TryParse("1.000", number); {
            if (number === 1) {
                this.decimalPoint = ".";
            }
            else {

                double.TryParse("1,000", number); {
                if (number === 1) {
                    this.decimalPoint = ",";
                }
            }
            if (this.decimalPoint === "") {
                throw new Exception(c_error_1);
            }
        }

UNKNOWN >>         public static string decimalPoint
        {
UNKNOWN >>             get
            {
                if (this.decimalPoint === "") {
                    throw new Exception(c_error_2);
                }
                else { return this.decimalPoint; }
            }
        }


    }    }
}
