(function(globalObject) {
﻿//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

    globalObject.CSReportEditor.Properties = globalObject.CSReportEditor.Properties || {};


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    globalObject.CSReportEditor.Properties.createResources = function() {

        // @ts-ignore
        let self: CSReportEditor.Properties.IResources = {};

        let global::System.Resources.ResourceManager: static = null;resourceMan;

        let global::System.Globalization.CultureInfo: static = null;resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        const Resources = function() {

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
UNKNOWN >>         internal static global::System.Resources.ResourceManager ResourceManager {
UNKNOWN >>             get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    let temp: global::System.Resources.ResourceManager = new global::System.Resources.ResourceManager("CSReportEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;

                return resourceMan;
            }
        };

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
UNKNOWN >>         internal static global::System.Globalization.CultureInfo Culture {
UNKNOWN >>             get {
                return resourceCulture;
            }
UNKNOWN >>             set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
UNKNOWN >>         internal static System.Drawing.Bitmap application_side_boxes {
UNKNOWN >>             get {
                let obj: object = ResourceManager.GetObject("application_side_boxes", resourceCulture);
                return ();
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
UNKNOWN >>         internal static System.Drawing.Bitmap config_page {
UNKNOWN >>             get {
                let obj: object = ResourceManager.GetObject("config_page", resourceCulture);
                return ();
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
UNKNOWN >>         internal static System.Drawing.Bitmap database_gear {
UNKNOWN >>             get {
                let obj: object = ResourceManager.GetObject("database_gear", resourceCulture);
                return ();
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
UNKNOWN >>         internal static System.Drawing.Bitmap disk {
UNKNOWN >>             get {
                let obj: object = ResourceManager.GetObject("disk", resourceCulture);
                return ();
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
UNKNOWN >>         internal static System.Drawing.Bitmap disk_multiple {
UNKNOWN >>             get {
                let obj: object = ResourceManager.GetObject("disk_multiple", resourceCulture);
                return ();
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
UNKNOWN >>         internal static System.Drawing.Bitmap find {
UNKNOWN >>             get {
                let obj: object = ResourceManager.GetObject("find", resourceCulture);
                return ();
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
UNKNOWN >>         internal static System.Drawing.Bitmap folder_page {
UNKNOWN >>             get {
                let obj: object = ResourceManager.GetObject("folder_page", resourceCulture);
                return ();
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
UNKNOWN >>         internal static System.Drawing.Bitmap lightning {
UNKNOWN >>             get {
                let obj: object = ResourceManager.GetObject("lightning", resourceCulture);
                return ();
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
UNKNOWN >>         internal static System.Drawing.Bitmap page {
UNKNOWN >>             get {
                let obj: object = ResourceManager.GetObject("page", resourceCulture);
                return ();
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
UNKNOWN >>         internal static System.Drawing.Bitmap page_landscape {
UNKNOWN >>             get {
                let obj: object = ResourceManager.GetObject("page_landscape", resourceCulture);
                return ();
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
UNKNOWN >>         internal static System.Drawing.Bitmap page_portrait {
UNKNOWN >>             get {
                let obj: object = ResourceManager.GetObject("page_portrait", resourceCulture);
                return ();
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
UNKNOWN >>         internal static System.Drawing.Bitmap printer {
UNKNOWN >>             get {
                let obj: object = ResourceManager.GetObject("printer", resourceCulture);
                return ();
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
UNKNOWN >>         internal static System.Drawing.Bitmap text_align_center {
UNKNOWN >>             get {
                let obj: object = ResourceManager.GetObject("text_align_center", resourceCulture);
                return ();
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
UNKNOWN >>         internal static System.Drawing.Bitmap text_align_left {
UNKNOWN >>             get {
                let obj: object = ResourceManager.GetObject("text_align_left", resourceCulture);
                return ();
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
UNKNOWN >>         internal static System.Drawing.Bitmap text_align_right {
UNKNOWN >>             get {
                let obj: object = ResourceManager.GetObject("text_align_right", resourceCulture);
                return ();
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
UNKNOWN >>         internal static System.Drawing.Bitmap text_bold {
UNKNOWN >>             get {
                let obj: object = ResourceManager.GetObject("text_bold", resourceCulture);
                return ();
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
UNKNOWN >>         internal static System.Drawing.Bitmap wrench {
UNKNOWN >>             get {
                let obj: object = ResourceManager.GetObject("wrench", resourceCulture);
                return ();
            }
        }
        return self;

    }    }
}(globalObject));


namespace CSReportEditor.Properties {

  export interface IResources {

  }
}
